### PR TITLE
Added more device features

### PR DESCRIPTION
**Pull request by NicknineTheEagle**
* android.hardware.touchscreen.multitouch.distinct (for com.mediocre.smashhit)
* GL_EXT_texture_compression_s3tc GL extension (for com.sega.sonic4ep2thd)

### CODE REVIEW

**Comment by 4cq2** [comment]
Going to repeat my comment from the other issue, because it seems to apply here:

I dont offer free support for any APK older than one year. So you if you can present evidence of a recent APK using this platform, then I will consider it. Or if you want to purchase paid support, contact me:

https://github.com/4cq2/googleplay#contact

otherwise, good luck.

**Comment by NicknineTheEagle** [comment]
Why is that relevant here? This PR is not asking for support, I literally did all the R&D myself, all you need to do is review PR and merge it. Comments in the code state which apps require the new feature tags.

**Comment by 4cq2** [comment]
I appreciate the work, but remember that I have to maintain any change forever. so its up to me to decide what feature are worth including. the one year rule is arbitrary, but seems fair to me. If you wish to present further arguments I am open to having a discussion. However again, if your goal is to have code added in support of old APKs, its going to be an uphill battle.

your best bet would be to find a new APK that has the same issue, or to pay for support. support includes me doing anything, even as small as clicking a merge button. I understand that might not be what you want to hear, but since I am the owner its on me to make these decisions.

**Comment by NicknineTheEagle** [comment]
Fine then. It is as they say, if you want something done right, do it yourself.

**Comment by 4cq2** [comment]
to anyone reading this page, the user above is a classic example of entitlement. the age of this repo is misleading, as its existed in other places before. So I will take a moment to say this project is something I have worked on for months and years, and offered the code for free. this user comes along and gets upset because I wont merge their precious code. I didn't close the PR, I discussed with them my reasons, and gave them multiple avenues on how to get their code merges.

**they refused** these options. So they did this to themself, not me.

**Comment by NicknineTheEagle** [comment]
Uh-huh, says the person who won't even accept *free* contribution without demanding to be paid for it. You don't get to talk about entitlement.

**Comment by 4cq2** [comment]
@NicknineTheEagle OK, consider this your one and only warning.

**Comment by 4cq2** [comment]
way late for this, but I wanted to add some more info for anyone who might visit this page. the struct being edited in this PR is here:

https://github.com/4cq2/googleplay/blob/7e53b18d99b99642b3a8250a5944e6b17c628f3c/checkin.go#L115

this device is just an example device. if you dont like it, you dont need to fork the entire codebase. You can just create your own device. For example, if you wanted a blank device (bad idea), you could create an use it like this:

~~~go
package main

import (
   "2a.pages.dev/googleplay"
   "fmt"
)

func main() {
   var config googleplay.Config
   res, err := config.Checkin("x86")
   if err != nil {
      panic(err)
   }
   defer res.Body.Close()
   fmt.Println(res.Status)
}
~~~

this is not a new change. the above program was even possible when the user here first posted their PR.

**Pull request closed without merging**
